---
abstract: 'provide the important mathematical constant tau = 6.2831...'
author:
  - 'Franklin Chen <franklinchen@franklinchen.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Tau
version: 1.003
